// LOCALHOST 
### Get all champions
 GET http://localhost:3300/champions

### Get champions by id 
GET http://localhost:3300/champions/65177a2979ed287b941161c1  
### 65177a2979ed287b941161c1

### Create champion 
POST http://localhost:3300/champions/ HTTP/1.1 
content-type: application/json

{
    "name": "Thresh",
    "lane": "Top",
    "type": ["Support", "Fighter"],
    "difficulty": "1",
    "resource": "Mana",
    "damage": "Ability Power",
    "number": "411"
}

### PUT champion 
PUT http://localhost:3300/champions/6506652867a79e685b213b1b HTTP/1.1 
content-type: application/json 

{
    "name": "Thresh",
    "lane": "Bottom",
    "type": ["Support", "Fighter"],
    "difficulty": "7",
    "resource": "Mana",
    "damage": "Ability Power",
    "number": "412"
}

### Delete champion 
DELETE http://localhost:3300/champions/65179fee3f3e663dcb2b09d9